[package]
name = "bobby-emu"
version = "0.0.0"
edition = "2024"

[dependencies]
anyhow = "1.0.97"
clap = { version = "4.5.31", features = ["derive"] }
crossterm = "0.28.1"
fps_counter = "3.0.0"
pixels = "0.15.0"
ratatui = "0.29.0"
winit = "0.29"
winit_input_helper = "0.15"
